import type { TSpirit } from "@/entities/spirit";

export const spirits: TSpirit[] = [
  {
    id: "1",
    name: "Banshee",
    threatLevel: "High",
    location: "Dublin",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Werwolf",
    threatLevel: "Critical",
    location: "Munich",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Vampire",
    threatLevel: "Medium",
    location: "Transylvania",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Goblin",
    threatLevel: "Low",
    location: "London",
    status: "Captured",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Poltergeist",
    threatLevel: "High",
    location: "Paris",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Succubus",
    threatLevel: "Medium",
    location: "Prague",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Draugr",
    threatLevel: "Critical",
    location: "Oslo",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Leprechaun",
    threatLevel: "Low",
    location: "Cork",
    status: "Active",
    lastSeen: new Date().toISOString(),
  },
];
